export const IconSettings = {
  appFlagSize: 32,
  buttonIconSize: 24,
  converterSectionIconSize: 32,
  countryFlagBorderRadius: 3,
  countryFlagMargin: 8,
  headerIconSize: 64,
  introductionIconSize: 200,
  introductionMiniIconSize: 32,
  listIconSize: 16,
  listsAvatarSize: 64,
  giftsInformationSize: 64,
  giftsChipSize: 38,
  modalHeadlineIconSize: 32,
  settingsFlagSize: 20,
  settingsSectionIconSize: 32,
  socialIconSize: 32,
  tabNavigationIconSize: 28,
  loadingIndicatorSize: 64,
  giftInformationIconSize: 64
};
